displayName=BrainrotSounds
author=collinod12
description=Replaces some sounds in Old School RuneScape with modern comical-relief
tags=death, sound, announce
version=
plugins=com.brainrotsounds.BrainrotSoundsPlugin
build=standard